"""Migrations and database constraints.

Each constraint test breaks one rule and checks that PostgreSQL rejects it *by constraint name*,
so we know the right rule fired (not some unrelated error).
"""

from collections.abc import Callable

import pytest
from alembic import command
from sqlalchemy import inspect, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db import engine
from app.models import (
    Base,
    Cart,
    CartItem,
    IdempotencyKey,
    Inventory,
    InventoryMovement,
    MovementReason,
    Product,
    Role,
    User,
)
from tests.conftest import alembic_config


def make_user(db: Session, email: str = "buyer@example.com", role: Role = Role.CUSTOMER) -> User:
    user = User(email=email, password_hash="not-a-real-hash", role=role)
    db.add(user)
    db.flush()
    return user


def make_product(db: Session, sku: str = "TSHIRT-BLK-M", price_paise: int = 49900, stock: int = 10) -> Product:
    product = Product(sku=sku, name="Black T-shirt", price_paise=price_paise)
    product.inventory = Inventory(quantity=stock)
    db.add(product)
    db.flush()
    return product


def assert_violates(db: Session, constraint_name: str, action: Callable[[], None]) -> None:
    with pytest.raises(IntegrityError) as exc_info:
        action()
        db.flush()
    assert constraint_name in str(exc_info.value.orig)
    db.rollback()


# --- migrations ---------------------------------------------------------------------------------


def test_migrations_downgrade_and_upgrade_cleanly() -> None:
    config = alembic_config()

    command.downgrade(config, "base")
    assert inspect(engine).get_table_names() == ["alembic_version"]

    command.upgrade(config, "head")
    expected = {table.name for table in Base.metadata.sorted_tables} | {"alembic_version"}
    assert set(inspect(engine).get_table_names()) == expected


def test_models_and_migrations_are_in_sync() -> None:
    # Fails (AutogenerateDiffsDetected) if a model changed without a matching migration.
    command.check(alembic_config())


# --- products & inventory -----------------------------------------------------------------------


def test_price_must_be_positive(db: Session) -> None:
    assert_violates(db, "ck_products_price_positive", lambda: make_product(db, price_paise=0))


@pytest.mark.parametrize("bad_sku", ["tshirt-blk", "TSHIRT BLK", "-TSHIRT", "TSHIRT--BLK", "AB"])
def test_sku_format_is_enforced(db: Session, bad_sku: str) -> None:
    assert_violates(db, "ck_products_sku_format", lambda: make_product(db, sku=bad_sku))


def test_sku_is_unique(db: Session) -> None:
    make_product(db, sku="MUG-WHITE")
    assert_violates(db, "uq_products_sku", lambda: make_product(db, sku="MUG-WHITE"))


def test_inventory_quantity_can_never_go_negative(db: Session) -> None:
    product = make_product(db, stock=1)
    db.commit()

    def oversell() -> None:
        product.inventory.quantity -= 2

    assert_violates(db, "ck_inventory_quantity_non_negative", oversell)


def test_movement_delta_cannot_be_zero(db: Session) -> None:
    product = make_product(db)
    assert_violates(
        db,
        "ck_inventory_movements_delta_non_zero",
        lambda: db.add(InventoryMovement(product_id=product.id, delta=0, reason=MovementReason.ADJUSTMENT)),
    )


# --- users --------------------------------------------------------------------------------------


def test_email_must_be_stored_lowercase(db: Session) -> None:
    assert_violates(db, "ck_users_email_lowercase", lambda: make_user(db, email="Buyer@Example.com"))


def test_role_is_restricted_to_known_values(db: Session) -> None:
    def insert_superuser() -> None:
        db.execute(text("INSERT INTO users (email, password_hash, role) VALUES ('x@example.com', 'h', 'superuser')"))

    assert_violates(db, "ck_users_role", insert_superuser)


def test_enums_are_stored_as_lowercase_values(db: Session) -> None:
    make_user(db, role=Role.ADMIN)

    stored = db.execute(text("SELECT role FROM users")).scalar_one()

    assert stored == "admin"


# --- carts & idempotency ------------------------------------------------------------------------


def test_one_cart_per_user(db: Session) -> None:
    user = make_user(db)
    db.add(Cart(user_id=user.id))
    db.flush()
    assert_violates(db, "uq_carts_user_id", lambda: db.add(Cart(user_id=user.id)))


@pytest.mark.parametrize("bad_quantity", [0, 101])
def test_cart_item_quantity_range(db: Session, bad_quantity: int) -> None:
    user = make_user(db)
    product = make_product(db)
    cart = Cart(user_id=user.id)
    db.add(cart)
    db.flush()
    assert_violates(
        db,
        "ck_cart_items_quantity_range",
        lambda: db.add(CartItem(cart_id=cart.id, product_id=product.id, quantity=bad_quantity)),
    )


def test_idempotency_key_is_unique_per_user(db: Session) -> None:
    user = make_user(db)
    db.add(IdempotencyKey(user_id=user.id, key="abc", request_hash="0" * 64))
    db.flush()
    assert_violates(
        db,
        "uq_idempotency_keys_user_id_key",
        lambda: db.add(IdempotencyKey(user_id=user.id, key="abc", request_hash="1" * 64)),
    )


def test_same_idempotency_key_is_allowed_for_different_users(db: Session) -> None:
    first = make_user(db, email="a@example.com")
    second = make_user(db, email="b@example.com")

    db.add_all(
        [
            IdempotencyKey(user_id=first.id, key="abc", request_hash="0" * 64),
            IdempotencyKey(user_id=second.id, key="abc", request_hash="0" * 64),
        ]
    )
    db.flush()  # no IntegrityError
