"""Migrations and database constraints.

Each constraint test breaks one rule and checks that PostgreSQL rejects it *by constraint name*,
so we know the right rule fired (not some unrelated error).
"""

import os
import subprocess
import sys
import time
from collections.abc import Callable

import pytest
from alembic import command
from sqlalchemy import inspect, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.constants import MIGRATION_ADVISORY_LOCK_ID
from app.db import engine
from app.models import (
    Base,
    Cart,
    CartItem,
    IdempotencyKey,
    Inventory,
    InventoryMovement,
    MovementReason,
    Product,
    Role,
    User,
)
from tests.conftest import BACKEND_DIR, alembic_config

PARALLEL_MIGRATIONS = 5
SUBPROCESS_TIMEOUT_SECONDS = 60


def make_user(db: Session, email: str = "buyer@example.com", role: Role = Role.CUSTOMER) -> User:
    user = User(email=email, password_hash="not-a-real-hash", role=role)
    db.add(user)
    db.flush()
    return user


def make_product(db: Session, sku: str = "TSHIRT-BLK-M", price_paise: int = 49900, stock: int = 10) -> Product:
    product = Product(sku=sku, name="Black T-shirt", price_paise=price_paise)
    product.inventory = Inventory(quantity=stock)
    db.add(product)
    db.flush()
    return product


def assert_violates(db: Session, constraint_name: str, action: Callable[[], None]) -> None:
    with pytest.raises(IntegrityError) as exc_info:
        action()
        db.flush()
    assert constraint_name in str(exc_info.value.orig)
    db.rollback()


# --- migrations ---------------------------------------------------------------------------------


def test_migrations_downgrade_and_upgrade_cleanly() -> None:
    config = alembic_config()

    command.downgrade(config, "base")
    assert inspect(engine).get_table_names() == ["alembic_version"]

    command.upgrade(config, "head")
    expected = {table.name for table in Base.metadata.sorted_tables} | {"alembic_version"}
    assert set(inspect(engine).get_table_names()) == expected


def test_models_and_migrations_are_in_sync() -> None:
    # Fails (AutogenerateDiffsDetected) if a model changed without a matching migration.
    command.check(alembic_config())


def _start_alembic_upgrade() -> subprocess.Popen:
    """A real `alembic upgrade head` in its own process, like a backend container starting.
    DATABASE_URL in os.environ already points at the test database (see conftest)."""
    return subprocess.Popen(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=BACKEND_DIR, env=dict(os.environ), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )


def _tables() -> set[str]:
    return set(inspect(engine).get_table_names()) - {"alembic_version"}


def test_migration_waits_for_the_advisory_lock() -> None:
    """While someone else holds the migration lock, `alembic upgrade` must wait instead of creating tables."""
    command.downgrade(alembic_config(), "base")
    holder = engine.connect()
    migration = None
    try:
        holder.execute(text("SELECT pg_advisory_lock(:id)"), {"id": MIGRATION_ADVISORY_LOCK_ID})
        migration = _start_alembic_upgrade()

        # Prove the process is *blocked on our lock*, not merely slow to start.
        deadline = time.monotonic() + SUBPROCESS_TIMEOUT_SECONDS
        while holder.execute(text("SELECT count(*) FROM pg_locks WHERE locktype = 'advisory' AND NOT granted")).scalar() == 0:
            assert migration.poll() is None, "migration finished without waiting for the lock:\n" + migration.stdout.read().decode()
            assert time.monotonic() < deadline, "migration never started waiting for the lock"
            time.sleep(0.1)
        assert _tables() == set()

        holder.execute(text("SELECT pg_advisory_unlock(:id)"), {"id": MIGRATION_ADVISORY_LOCK_ID})
        output = migration.communicate(timeout=SUBPROCESS_TIMEOUT_SECONDS)[0].decode()
        assert migration.returncode == 0, output
        assert _tables() == {table.name for table in Base.metadata.sorted_tables}
    finally:
        holder.close()
        if migration and migration.poll() is None:
            migration.kill()
        command.upgrade(alembic_config(), "head")  # leave the test DB migrated for the other tests


def test_containers_starting_together_all_migrate_successfully() -> None:
    """Five `alembic upgrade head` processes on an empty database at once: all must exit 0."""
    command.downgrade(alembic_config(), "base")
    try:
        processes = [_start_alembic_upgrade() for _ in range(PARALLEL_MIGRATIONS)]
        outputs = [p.communicate(timeout=SUBPROCESS_TIMEOUT_SECONDS)[0].decode() for p in processes]

        assert [p.returncode for p in processes] == [0] * PARALLEL_MIGRATIONS, "\n---\n".join(outputs)
        assert _tables() == {table.name for table in Base.metadata.sorted_tables}
    finally:
        command.upgrade(alembic_config(), "head")


# --- products & inventory -----------------------------------------------------------------------


def test_price_must_be_positive(db: Session) -> None:
    assert_violates(db, "ck_products_price_positive", lambda: make_product(db, price_paise=0))


@pytest.mark.parametrize("bad_sku", ["tshirt-blk", "TSHIRT BLK", "-TSHIRT", "TSHIRT--BLK", "AB"])
def test_sku_format_is_enforced(db: Session, bad_sku: str) -> None:
    assert_violates(db, "ck_products_sku_format", lambda: make_product(db, sku=bad_sku))


def test_sku_is_unique(db: Session) -> None:
    make_product(db, sku="MUG-WHITE")
    assert_violates(db, "uq_products_sku", lambda: make_product(db, sku="MUG-WHITE"))


def test_inventory_quantity_can_never_go_negative(db: Session) -> None:
    product = make_product(db, stock=1)
    db.commit()

    def oversell() -> None:
        product.inventory.quantity -= 2

    assert_violates(db, "ck_inventory_quantity_non_negative", oversell)


def test_movement_delta_cannot_be_zero(db: Session) -> None:
    product = make_product(db)
    assert_violates(
        db,
        "ck_inventory_movements_delta_non_zero",
        lambda: db.add(InventoryMovement(product_id=product.id, delta=0, reason=MovementReason.ADJUSTMENT)),
    )


# --- users --------------------------------------------------------------------------------------


def test_email_must_be_stored_lowercase(db: Session) -> None:
    assert_violates(db, "ck_users_email_lowercase", lambda: make_user(db, email="Buyer@Example.com"))


def test_role_is_restricted_to_known_values(db: Session) -> None:
    def insert_superuser() -> None:
        db.execute(text("INSERT INTO users (email, password_hash, role) VALUES ('x@example.com', 'h', 'superuser')"))

    assert_violates(db, "ck_users_role", insert_superuser)


def test_enums_are_stored_as_lowercase_values(db: Session) -> None:
    make_user(db, role=Role.ADMIN)

    stored = db.execute(text("SELECT role FROM users")).scalar_one()

    assert stored == "admin"


# --- carts & idempotency ------------------------------------------------------------------------


def test_one_cart_per_user(db: Session) -> None:
    user = make_user(db)
    db.add(Cart(user_id=user.id))
    db.flush()
    assert_violates(db, "uq_carts_user_id", lambda: db.add(Cart(user_id=user.id)))


@pytest.mark.parametrize("bad_quantity", [0, 101])
def test_cart_item_quantity_range(db: Session, bad_quantity: int) -> None:
    user = make_user(db)
    product = make_product(db)
    cart = Cart(user_id=user.id)
    db.add(cart)
    db.flush()
    assert_violates(
        db,
        "ck_cart_items_quantity_range",
        lambda: db.add(CartItem(cart_id=cart.id, product_id=product.id, quantity=bad_quantity)),
    )


def test_idempotency_key_is_unique_per_user(db: Session) -> None:
    user = make_user(db)
    db.add(IdempotencyKey(user_id=user.id, key="abc", request_hash="0" * 64))
    db.flush()
    assert_violates(
        db,
        "uq_idempotency_keys_user_id_key",
        lambda: db.add(IdempotencyKey(user_id=user.id, key="abc", request_hash="1" * 64)),
    )


def test_same_idempotency_key_is_allowed_for_different_users(db: Session) -> None:
    first = make_user(db, email="a@example.com")
    second = make_user(db, email="b@example.com")

    db.add_all(
        [
            IdempotencyKey(user_id=first.id, key="abc", request_hash="0" * 64),
            IdempotencyKey(user_id=second.id, key="abc", request_hash="0" * 64),
        ]
    )
    db.flush()  # no IntegrityError
