"""Initial schema: users, catalogue, inventory + ledger, carts, orders, idempotency keys.

Revision ID: 0001
Revises:
Create Date: 2026-09-26

Drafted with `alembic revision --autogenerate`, then rewritten by hand: tables ordered by dependency,
and each enum stored as VARCHAR(20) with exactly one named CHECK constraint (the autogenerated draft
emitted every enum CHECK twice). CHECK names are wrapped in op.f() so the
metadata naming convention (ck_<table>_<name>) isn't applied a second time.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _id() -> sa.Column:
    return sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False)


def _timestamp(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def upgrade() -> None:
    op.create_table(
        "users",
        _id(),
        sa.Column("email", sa.String(254), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        _timestamp("created_at"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.CheckConstraint("role IN ('customer', 'admin')", name=op.f("ck_users_role")),
    )

    op.create_table(
        "products",
        _id(),
        sa.Column("sku", sa.String(64), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("id", name="pk_products"),
        sa.UniqueConstraint("sku", name="uq_products_sku"),
        sa.CheckConstraint("price_paise > 0", name=op.f("ck_products_price_positive")),
        sa.CheckConstraint("sku ~ '^[A-Z0-9]+(-[A-Z0-9]+)*$' AND length(sku) >= 3", name=op.f("ck_products_sku_format")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_products_name_not_blank")),
    )

    op.create_table(
        "inventory",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), server_default="5", nullable=False),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("product_id", name="pk_inventory"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name="fk_inventory_product_id_products"),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_inventory_quantity_non_negative")),
        sa.CheckConstraint("low_stock_threshold >= 0", name=op.f("ck_inventory_threshold_non_negative")),
    )

    op.create_table(
        "orders",
        _id(),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("shipping_address", sa.Text(), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("id", name="pk_orders"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_orders_user_id_users"),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'shipped', 'cancelled')", name=op.f("ck_orders_order_status")
        ),
        sa.CheckConstraint("total_paise > 0", name=op.f("ck_orders_total_positive")),
        sa.CheckConstraint("length(trim(shipping_address)) > 0", name=op.f("ck_orders_address_not_blank")),
    )
    op.create_index("ix_orders_user_id_created_at", "orders", ["user_id", "created_at"])

    op.create_table(
        "order_items",
        _id(),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_order_items"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name="fk_order_items_order_id_orders"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name="fk_order_items_product_id_products"),
        # Also serves as the index for "items of order X" (order_id is its first column).
        sa.UniqueConstraint("order_id", "product_id", name="uq_order_items_order_id_product_id"),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint("unit_price_paise > 0", name=op.f("ck_order_items_unit_price_positive")),
    )

    op.create_table(
        "inventory_movements",
        _id(),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(20), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        _timestamp("created_at"),
        sa.PrimaryKeyConstraint("id", name="pk_inventory_movements"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name="fk_inventory_movements_product_id_products"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name="fk_inventory_movements_order_id_orders"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], name="fk_inventory_movements_actor_user_id_users"),
        sa.CheckConstraint("delta <> 0", name=op.f("ck_inventory_movements_delta_non_zero")),
        sa.CheckConstraint(
            "reason IN ('restock', 'order', 'cancel', 'adjustment')", name=op.f("ck_inventory_movements_movement_reason")
        ),
    )
    op.create_index(
        "ix_inventory_movements_product_id_created_at", "inventory_movements", ["product_id", "created_at"]
    )

    op.create_table(
        "carts",
        _id(),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("id", name="pk_carts"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_carts_user_id_users"),
        sa.UniqueConstraint("user_id", name="uq_carts_user_id"),
    )

    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        _timestamp("added_at"),
        sa.PrimaryKeyConstraint("cart_id", "product_id", name="pk_cart_items"),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], name="fk_cart_items_cart_id_carts"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name="fk_cart_items_product_id_products"),
        sa.CheckConstraint("quantity BETWEEN 1 AND 100", name=op.f("ck_cart_items_quantity_range")),
    )

    op.create_table(
        "idempotency_keys",
        _id(),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(255), nullable=False),
        sa.Column("request_hash", sa.CHAR(64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(), nullable=True),
        _timestamp("created_at"),
        sa.PrimaryKeyConstraint("id", name="pk_idempotency_keys"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_idempotency_keys_user_id_users"),
        sa.UniqueConstraint("user_id", "key", name="uq_idempotency_keys_user_id_key"),
    )


def downgrade() -> None:
    # Reverse dependency order: children before the tables they reference.
    op.drop_table("idempotency_keys")
    op.drop_table("cart_items")
    op.drop_table("carts")
    op.drop_index("ix_inventory_movements_product_id_created_at", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_table("order_items")
    op.drop_index("ix_orders_user_id_created_at", table_name="orders")
    op.drop_table("orders")
    op.drop_table("inventory")
    op.drop_table("products")
    op.drop_table("users")
